### ISSUE TITLE
Code commenting

### ISSUE THREAD

**Issue by Toeffe3** [BHelpful/Mealplanr#108]
- [x] Comment all pure JS functions 
- [x] Comment all components
- [x] Comment CSS documents

**Comment by Andreasgdp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MealPlanr-Management-6117db8376d3b50017bfb990/issues/BHelpful/Mealplanr/108?planning-poker) with ZenHub @Toeffe3
