### ISSUE TITLE
Recipe showcase top selection area

### ISSUE THREAD

**Issue by Andreasgdp** [BHelpful/Mealplanr#70]
## Short description of a problem or missing feature

Expected look
![image](https://user-images.githubusercontent.com/39928082/128636759-19df9862-44ed-4b32-813f-4d1852da83e7.png)
Current look
![image](https://user-images.githubusercontent.com/39928082/128636764-080de100-afe4-4eb2-a017-b1155990f88b.png)

- [x] Image needs to be bigger (the description does not need to be that long)
- [x] The rating needs to be shown correctly (if it is public)
- [x] Add a switch of some sort to enable the recipe to be public.

![image](https://user-images.githubusercontent.com/39928082/128636821-bdf3a3f3-6549-44eb-adf4-32a30f4453e5.png)

**Comment by Toeffe3** [comment]
Public-status toggle should be in create/edit recipie and not in this issue
